---
title: "all_st_by_steam"
author: "Rasool Saghaleyni"
date: "2025-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:
```{r, message=FALSE}
library(dplyr)
library(RColorBrewer)
library(scales)
library(reshape2)
library(corrplot)
library(lawstat)
library(MASS)
library(viridis)
library(steam)
library(STutility)
```

Load ST data:
```{r}
infoTable <- read.csv("data/Data_brain_example/spatial_data/infoTable.csv", sep = ";")

se <- InputFromTable(infotable = infoTable, 
                    minUMICountsPerGene = 100, 
                    minSpotsPerGene = 5,
                    minUMICountsPerSpot = 500,
                    platform = "Visium")

# Load images
se <- LoadImages(se, time.resolve = FALSE)

# Add some dummy cluster annotations
se$cluster_anno <- sample(1:5, ncol(se), replace = TRUE)

# Create a simple window rank list for testing
test_genes <- head(rownames(se), 50)  # Take first 50 genes
test_window_list <- list(test_genes)

# Add dummy enrichment scores to metadata
# The function expects scores in the format: DISEASE_LABEL_RankN_1
se$TEST_Test_Rank1_1 <- runif(ncol(se))  # Add random scores for testing

# Test the feature plot
featurePlotForRanks(
    se = se,
    window_rank_list = test_window_list,
    ot_gene_set_label = "Test",
    disease_abbr = "TEST",
    ranks_per_plot = 1,
    spot_alpha = 0.5,
    point_size = 1,
    all_clusters = TRUE,
    cluster_anno = "cluster_anno",
    seurat_type = "stutility"
)
```


